### ISSUE TITLE
Petclinic devfile out of date

### ISSUE THREAD

**Issue by jarifibrahim** [redhat-developer/devfile#4]
The following curl request to create a new workspace returns error
```
$ curl -X POST --header 'Content-Type: text/yaml' --header 'Accept: application/json' -d '---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: \u0027git@github.com:spring-projects/spring-petclinic.git\u0027
tools:
  - name: mvn-stack
    type: dockerImage
    image: maven:3.5.4-jdk-8
    entryPoint: sleep infinity
    persistentVolumes:
      - name: maven-repo
        containerPath: /root/.m2
    services:
      - name: spring-boot
        port: 8080
    mountProjectsSources: true
  - name: mysql
    type: kubernetes
    local: petclinic.yaml
    selector:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: petclinic
  - name: theia-ide
    type: cheEditor
    id: eclipse/theia:0.0.3
  - name: jdt.ls
    type: chePlugin
    id: eclipse/theia-jdtls:0.0.3
commands:
  - name: build
    actions:
      - type: exec
        tool: mvn-stack
        command: mvn package
        workdir: /projects/spring-petclinic
  - name: run
    attributes:
      runType: sequential
    actions:
      - type: start
        tool: mysql
        timeout: 20s
      - type: exec
        tool: mvn-stack
        command: mvn spring-boot:run
        workdir: /projects/spring-petclinic
' 'http://che-mini-che.192.168.42.178.nip.io/api/devfile?verbose=false'
```

It returns
```

{
  "message": "Devfile schema validation failed. Errors: [object has missing required properties ([\"command\"])]"
}
```

The error is returned because the `tool: mysql` section doesn't have `command` block
```
  - name: run
    attributes:
      runType: sequential
    actions:
      - type: start
        tool: mysql
        timeout: 20s
```

**Comment by sleshchenko** [comment]
@jarifibrahim Thanks for reporting. Will take into account. But this repository contains concept description and some of the things in `Devfile` example are not implemented yet.

**Comment by jarifibrahim** [comment]
@sleshchenko Is there a sample devfile that I can use? I'm trying to figure out how we can use the devfiles on OSIO.

**Comment by sleshchenko** [comment]
@jarifibrahim No, you can not use it for now.
@l0rd We should consider adding another `Devfile` sample that would contain only those things which are implemented. WDYT?

**Comment by sleshchenko** [comment]
@mshaposhnik Could you provide a `Devfile` sample that is can be used on OSIO? Note it is not updated to latest Che Vestion and `plugin`, `editor` tools only are supported there.

**Comment by jarifibrahim** [comment]
>@mshaposhnik Could you provide a Devfile sample that is can be used on OSIO? 

This one https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-devfile/src/test/resources/devfile.yaml  seems to work. The workspace was created but it didn't start 
```
Error: Failed to run the workspace: "Metadata of plugin maven-jdk8:1.0.0 retrieval failed. Error is URI is not absolute"
```

**Comment by mshaposhnik** [comment]
You picked just test source yaml, so some plugins are dummy in it (like jdk one).

**Comment by jarifibrahim** [comment]
Yes, the following yaml create a workspace but the terminal doesn't work. I've raised https://github.com/eclipse/che/issues/12451
```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: terminal
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
commands:
  - name: hello
    actions:
      - type: exec
        tool: theia-ide
        command: echo Hello
        workdir: /projects/spring-petclinic
```
